title: Stories
email: wackyblackie@outlook.com
description: Copy of stories that we read, all from 1lib.us.
github_username: wackyblackie

include: ['_pages']
permalink: /:pubyear/:pubmonth/:pubday/:title

# Build settings
theme: minima
plugins:
  - jekyll-feed
